package com.mygdx.game.gamescreen.cards;

public enum Items {
    SCHEME_CARD,
    WORKER_CARD,
    RESOURSE_CARD,
    SCHEME_BUILDING,
    WORKER_BUILDING,
    RESOURSE_BUILDING,
    ENERGY_BUILDING,
    QUICKBUILD_UPGRADE,
    DEMOLISHBUILD_UPGRADE,
    ACTIVATEBUILD_UPGRADE
}
